# Generated by Django 4.2.1 on 2023-12-19 17:22

from django.db import migrations, models
import producto.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('ACCESORIOS', 'Accesorios'), ('RESPUESTOS', 'Repuestos'), ('CONSUMIBLES', 'Consumibles')], max_length=11, verbose_name='Categoria')),
                ('nombre', models.CharField(max_length=45, validators=[producto.models.letras_validator], verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=60, validators=[producto.models.letras_validator], verbose_name='Descripcion')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio')),
                ('stock', models.PositiveIntegerField(verbose_name='Stock')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo'), ('2', 'Condicionado')], default='1', max_length=2, verbose_name='Estado')),
            ],
        ),
    ]
